services:

  database:
    build: .
    command: uvicorn database:app --host 0.0.0.0 --port 8080  # Listen on all interfaces
    networks:
      - internal_network

  map:
    build: .
    command: uvicorn map:app --host 0.0.0.0 --port 5000
    networks:
      - internal_network
    depends_on:
      - database  # Ensures database starts before backend

  login:
    build: .
    command: uvicorn login:app --host 0.0.0.0 --port 6000
    networks:
      - internal_network
    depends_on:
      - database  # Ensures database starts before backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/trainer-trade/static
    ports:
      - "8000:80"
    depends_on:
      - login
      - map
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
